### ISSUE TITLE
Subdomain Tenant Wrong Database Sanctum

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [stancl/tenancy#944] opened 2022-09-08 23:47 UTC
### Bug description

Hi team,

I'm testing the library and I follow the steps on the documentation.

My main issue is when I try to register a new user using sanctum.

### Steps to reproduce

So I have the next configuration:

**tenant.php**

```
Route::middleware([
    'web',
    InitializeTenancyBySubdomain::class,
    PreventAccessFromCentralDomains::class,
])->group(function () {
    Route::get('/', function () {
        return 'This is your multi-tenant application. The id of the current tenant is ' . tenant('id');
    });
});
```

**tenancy.php**

```
'tenant_model' => \App\Models\Tenant::class,
    'id_generator' => Stancl\Tenancy\UUIDGenerator::class,

    'domain_model' => Domain::class,

    /**
     * The list of domains hosting your central app.
     *
     * Only relevant if you're using the domain or subdomain identification middleware.
     */
    'central_domains' => [
        '127.0.0.1',
        'localhost',
        'dominio.com'
    ],
```

I just access to the domain.

**http://foo.dominio.com/register**

But when I try to register my user it uses the default database not the foo databases.

**.env**

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=saturn_testing
DB_USERNAME=root
DB_PASSWORD=realhost
```

```
mysql> select * from domains;
+----+-------------+-----------+---------------------+---------------------+
| id | domain      | tenant_id | created_at          | updated_at          |
+----+-------------+-----------+---------------------+---------------------+
|  1 | dominio.com | foo       | 2022-09-08 22:54:12 | 2022-09-08 22:54:12 |
+----+-------------+-----------+---------------------+---------------------+
```

```
mysql> select * from tenants;
+-----+---------------------+---------------------+----------------------------------+
| id  | created_at          | updated_at          | data                             |
+-----+---------------------+---------------------+----------------------------------+
| foo | 2022-09-08 22:54:01 | 2022-09-08 22:54:01 | {"tenancy_db_name": "tenantfoo"} |
+-----+---------------------+---------------------+----------------------------------+
```

On app/Actions/Fortify/CreateNewUser.php

I just print the database:

```
return DB::transaction(function () use ($input) {
            dd(DB::connection()->getDatabaseName());
            return tap(User::create([
                'name' => $input['name'],
                'taxref' => $input['taxref'],
                'regime' => $input['regime'],
                'use_cfdi' => $input['use_cfdi'],
                'email' => $input['email'],
                'password' => Hash::make($input['password']),
            ]), function (User $user) {
                $this->createTeam($user);
            });
        });
```

it shows "saturn_testing", am I missing something?

### Expected behavior

Use the tenant database

### Laravel version

^9.19

### stancl/tenancy version

^3.5

**Comment by stancl** [comment] 2022-09-09 17:02
Seems like you didn't make Sanctum use Tenancy, if you want to ask a support question you can use [our Discord](https://archte.ch/discord). Closing this as it's not a bug in the package.

**Closed as completed by stancl** 2022-09-09 17:02 UTC
Labels: bug
