### ISSUE TITLE
migrate-fresh command don't consider mysql-schema.dump  file

### ISSUE THREAD

**Issue by arivelli** [stancl/tenancy#978] opened 2022-10-15 22:27 UTC
### Bug description

When I run my migrations the schema files are not considered

### Steps to reproduce

sail artisan tenants:migrate-fresh

### Expected behavior

consider the file mysql-schema.dump

### Laravel version

^9.19

### stancl/tenancy version

3.6

**Comment by stancl** [comment] 2022-10-16 16:42
- Dumping tenant schemas is not a v3 feature
- We use a custom implementation for migrate:fresh. Why exactly is not using the dump file a problem?

**Comment by arivelli** [comment] 2022-10-16 17:50
Hey stancl,

Thanks for answer, it's beacuse I have my migration removed and I only have this mysql-schema.dump file, so, whenever I create a new domain I need to run the dump file manually instead of using artisan migrate as usual.

Regards

**Comment by stancl** [comment] 2022-10-16 18:01
I see, that's fair. We'll take a look at this.

@lukinovec as part of some of the tasks we're doing now, we should verify that all migration commands work even when schema is used instead of migration classes (since the migrations can be deleted after the schema dump is created). I *think* `migrate` can have parameters specified in the config, but `migrate:fresh` probably doesn't respect this.

I'm not sure if we want to use the schema automatically in `migrate`, probably not (so users who generate the schema should then configure it in the config), but `migrate:fresh` should take all of the parameters from the config for the `migrate` call it does.

**Comment by arivelli** [comment] 2022-10-16 18:49
Thanks Samuel,

In my humble opinion I think it should be as close as possible to how `php artisan migrate` works.

**Comment by lukinovec** [comment] 2022-10-17 08:58
@stancl, just to confirm, we're talking about `tenants:migrate-fresh` and `tenants:migrate`, not the Laravel commands (`migrate:fresh`) here, right?

> migrate:fresh should take all of the parameters from the config for the migrate call it does

Right, I see that `tenants:migrate` and `tenants:rollback` respect parameters from the `tenancy.migration_parameters` config, but `migrate:fresh` doesn't. `tenants:migrate-fresh` calls  `tenants:migrate` with `--tenants=[$tenantKey]` and `--force=true`, nothing else is passed to the command.

**Comment by stancl** [comment] 2022-10-17 09:09
Yeah, we probably just want to merge in the params from config

**Comment by lukinovec** [comment] 2022-10-24 13:26
> tenants:migrate-fresh calls tenants:migrate with --tenants=[$tenantKey] and --force=true, nothing else is passed to the command.

This is not relevant in the end. `tenants:migrate` gets the options from the config even if they weren't passed to the command. The paths from the config are passed to `MigrateCommand` (doesn't matter if we call `tenants:migrate` or `tenants:migrate-fresh`). I'll try reproducing the issue.

**Comment by lukinovec** [comment] 2022-10-24 15:01
So this really doesn't look like a `tenants:migrate-fresh` issue @stancl. The dump is also not considered with `tenants:migrate`.

I had some migrations in `migrations/tenant` and a tenant with a database that had some data. I dumped the migrations using the v4 dump command, and I removed the tenant migrations. Then, I used `tenants:migrate-fresh` to clear the tenant database and see if the database's tables wiped and then created. They didn't get created. I called `tenants:migrate`, and that also didn't create the tables.

![image](https://user-images.githubusercontent.com/34375937/197558836-f6057a68-9105-41ad-b8be-4109d18f942b.png)
(no output about the dump being used)


My migration parameters config:
```php
'migration_parameters' => [
    '--force' => true, // This needs to be true to run migrations in production.
    '--path' => [database_path('migrations/tenant')],
    '--realpath' => true,
],
```

Also, the dump file is `database/schema/mysql-schema.dump`, and that's the same name as the name of the dump that'd be used for the central app (as @stancl wrote [here](https://3.basecamp.com/5170965/buckets/23651018/todos/5445406155)). `migrate:fresh` considers that dump.
![image](https://user-images.githubusercontent.com/34375937/197558741-7a462659-5bbb-4506-9b04-592dd6a37a16.png)

**Comment by stancl** [comment] 2022-10-24 19:55
Closing this since the logic works as expected — `tenants:migrate-fresh` uses the parameters specified in the config since it calls `tenants:migrate` internally.

Regarding the dump file, we'll be changing how that works in v4 to use a separate file from the central one.

**Closed as not planned by stancl** 2022-10-24 19:55 UTC
Labels: v4

**Comment by arivelli** [comment] 2022-10-25 15:41
Hey, maybe I'm wrong but IMO its not working properly, as you said `tenants:migrate-fresh` calls `tenants:migrate` and it calls `migrate` and in this case should call `migrate:fresh` (which is a different command).

**Comment by stancl** [comment] 2022-10-25 15:45
It calls `db:wipe` and then `tenants:migrate`. We can't call `migrate:fresh` directly from `tenants:migrate`.

**Comment by stancl** [comment] 2022-10-25 15:45
Either way — schema dumps are not something that's supported in v3.

**Comment by tomasvanrijsse** [comment] 2022-11-11 13:35
I faced this same issue, and I'm looking forward to v4.
Untill then, this issue is easily resolved by running the schema dump in a migration that runs first:

`/database/migrations/tenant/0000_00_00_000000_execute_schema_dump.php`
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up()
    {
        DB::statement(file_get_contents(__DIR__.'/../../schema/mysql-schema.dump'));
    }
};
```

**Comment by tomasvanrijsse** [comment] 2022-11-11 14:01
I've solved this for now using a migration that will run the schema dump.

1. Move your schema folder to the tenants folder (otherwise it will run the schema in the central database)
2. Create a migration that will run first e.g. `/database/migrations/tenants/0000_00_00_000000_execute_schema_dump.php`

```php
<?php

use Illuminate\Database\Migrations\Migration;

return new class extends Migration {
    public function up()
    {
        Artisan::call('migrate', [
             '--schema-path' => __DIR__.'/schema/mysql-schema.dump',
             '--path' => '/dev/null'
        ]);
    }
};

```
