### ISSUE TITLE
Cache::increment('key'); return null

### ISSUE THREAD

**Issue by popfaker** [stancl/tenancy#983] opened 2022-10-22 08:57 UTC
### Bug description

In `tenancy.bootstrappers` ,use `Stancl\Tenancy\Bootstrappers\CacheTenancyBootstrapper::class`

$value = Cache::increment('key');
$value is null

### Steps to reproduce

use `Stancl\Tenancy\Bootstrappers\CacheTenancyBootstrapper::class`

### Expected behavior

Use `Cache::increment('key');`
The return value is correct

### Laravel version

6.20.44

### stancl/tenancy version

3.4.6

**Comment by stancl** [comment] 2022-10-22 13:44
What cache driver are you using?

**Comment by popfaker** [comment] 2022-10-23 03:36
> What cache driver are you using?

Use `redis`
In .env   `CACHE_DRIVER=redis`

**Comment by stancl** [comment] 2022-10-23 10:15
Try updating Laravel and Tenancy, it seems like you're using unsupported versions.

**Comment by stancl** [comment] 2022-10-24 19:57
@lukinovec Try to repro this. It's *possible* that `increment()` wouldn't work (compared to `get()` and `set()`) with the cache tenancy bootstrapper, but it's unlikely.

**Comment by lukinovec** [comment] 2022-10-26 11:08
I couldn't reproduce this @stancl. `Cache::get('key')` returns `null` since the key isn't set yet, then `Cache::increment('key')` returns `1`, and then `Cache::get('key')` returns `"1"` – so increment did change the value from `null` to `"1"`, which seems correct.

`CACHE_DRIVER=redis`
`"stancl/tenancy": "^3.5"`
`"laravel/framework": "^9.19"`

**Comment by stancl** [comment] 2022-10-26 12:17
Is this with the bootstrapper enabled? And using `Cache` in tenant context

**Comment by lukinovec** [comment] 2022-10-26 13:18
Yes to both

**Comment by stancl** [comment] 2022-10-26 13:22
Thanks for testing that. Closing this as we can't reproduce the issue.

**Closed as completed by stancl** 2022-10-26 13:22 UTC
Labels: bug

**Comment by popfaker** [comment] 2022-10-27 06:19
> Thanks for testing that. Closing this as we can't reproduce the issue.

Tenant bootstrapper has been enabled.  And using `Cache` In tenant contenxt
I tried to use `Cache:: increment ('key ')` to return null, but `Cache:: get ('key')` is correct, and the extension I used is 'phpredis'

I'll try to see if there is this problem in larravel 9. Thank you.

**Comment by popfaker** [comment] 2022-10-27 06:52
> Thanks for testing that. Closing this as we can't reproduce the issue.

Like this
![demo](https://user-images.githubusercontent.com/38718383/198211396-62a04aa7-cf74-458e-ab93-67b1bd460d76.gif)

```
CACHE_DRIVER=redis
"stancl/tenancy": "3.4.6"
"laravel/framework": "6.20.44"
```
cache.php
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Cache Store
    |--------------------------------------------------------------------------
    |
    | This option controls the default cache connection that gets used while
    | using this caching library. This connection is used when another is
    | not explicitly specified when executing a given caching function.
    |
    | Supported: "apc", "array", "database", "file", "memcached", "redis"
    |
    */

    'default' => env('CACHE_DRIVER', 'file'),

    /*
    |--------------------------------------------------------------------------
    | Cache Stores
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the cache "stores" for your application as
    | well as their drivers. You may even define multiple stores for the
    | same cache driver to group types of items stored in your caches.
    |
    */

    'stores' => [

        'apc' => [
            'driver' => 'apc',
        ],

        'array' => [
            'driver' => 'array',
        ],

        'database' => [
            'driver' => 'database',
            'table' => 'cache',
            'connection' => null,
        ],

        'file' => [
            'driver' => 'file',
            'path' => storage_path('framework/cache/data'),
        ],

        'memcached' => [
            'driver' => 'memcached',
            'persistent_id' => env('MEMCACHED_PERSISTENT_ID'),
            'sasl' => [
                env('MEMCACHED_USERNAME'),
                env('MEMCACHED_PASSWORD'),
            ],
            'options' => [
                // Memcached::OPT_CONNECT_TIMEOUT  => 2000,
            ],
            'servers' => [
                [
                    'host' => env('MEMCACHED_HOST', '127.0.0.1'),
                    'port' => env('MEMCACHED_PORT', 11211),
                    'weight' => 100,
                ],
            ],
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],

        'business' => [
            'driver' => 'redis',
            'connection' => 'cache',
        ],

        'clue_redis' => [
            'driver' => 'redis',
            'connection' => 'clue',
        ]

    ],

    /*
    |--------------------------------------------------------------------------
    | Cache Key Prefix
    |--------------------------------------------------------------------------
    |
    | When utilizing a RAM based store such as APC or Memcached, there might
    | be other applications utilizing the same cache. So, we'll specify a
    | value to get prefixed to all our keys so we can avoid collisions.
    |
    */

    'prefix' => env(
        'CACHE_PREFIX',
        str_slug(env('APP_NAME', 'laravel'), '_') . '_cache'
    ),

];

```
