### ISSUE TITLE
LOG.warning tenantIdColumn is deprecated

### ISSUE THREAD

**Issue by emerson-oliveira** [stancl/tenancy#1225] opened 2024-05-18 16:08 UTC
## Bug description

I am encountering a warning when using the Tenancy package. The warning indicates that accessing a static trait property is deprecated. Below is the full log message:

```php
LOG.warning: Accessing static trait property Stancl\Tenancy\Database\Concerns\BelongsToTenant::$tenantIdColumn is deprecated, it should only be accessed on a class using the trait in C:\laragon\www\dysrup-web\vendor\stancl\tenancy\src\Database\Concerns\BelongsToTenant.php on line 19
```

### Actual Behavior
The following deprecation warning is logged:

```php
LOG.warning: Accessing static trait property Stancl\Tenancy\Database\Concerns\BelongsToTenant::$tenantIdColumn is deprecated, it should only be accessed on a class using the trait in C:\laragon\www\dysrup-web\vendor\stancl\tenancy\src\Database\Concerns\BelongsToTenant.php on line 19
```

### Steps to reproduce

1. Install the Tenancy package in a Laravel project.
2. Trigger any functionality that uses the BelongsToTenant trait.
3. Observe the warning in the logs.

### Expected behavior

No deprecation warnings should be logged.

### Laravel version

9.52.16

### stancl/tenancy version

3.8.3

Environment
PHP version: 8.1
Operating System: Ubuntu 20.04

**Comment by stancl** [comment] 2024-05-18 16:11
Duplicate of https://github.com/archtechx/tenancy/issues/854

Fixed in v4, can't be fixed in v3 without breaking changes.

**Closed as completed by stancl** 2024-05-18 16:11 UTC
Labels: bug, duplicate

**Comment by damms005** [comment] 2024-09-17 19:06
Any hint on v4 release timeline? @stancl

**Comment by stancl** [comment] 2024-09-17 19:51
Updates are posted on our Discord.
